export enum EReduxActionTypes {
  // perspective
  SET_PERSPECTIVE = 'SET_PERSPECTIVE',

  // connection
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',

  // world
  RESET_WORLD = "RESET_WORLD",
  UPDATE_WORLD = "UPDATE_WORLD",

  // runtime meas
  SHOW_RUNTIME_MEAS = "SHOW_RUNTIME_MEAS",
  HIDE_RUNTIME_MEAS = "HIDE_RUNTIME_MEAS",
}
