export enum EReduxActionTypes {
  // perspective
  SET_PERSPECTIVE = 'SET_PERSPECTIVE',

  // connection
  SET_CONNECTING = 'SET_CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  WAIT_FOR_DATA = "WAIT_FOR_DATA",
  SET_HOST = "SET_HOST",

  // world
  RESET_WORLD = "RESET_WORLD",
  UPDATE_WORLD = "UPDATE_WORLD",

  // ctrl data
  UPDATE_CTRL_DATA = "UPDATE_CTRL_DATA",
  RESET_CTRL_DATA = "RESET_CTRL_DATA",

  // runtime meas
  SHOW_RUNTIME_MEAS = "SHOW_RUNTIME_MEAS",
  HIDE_RUNTIME_MEAS = "HIDE_RUNTIME_MEAS",
  ADD_RUNTIME_MEAS = "ADD_RUNTIME_MEAS",
  CLEAR_RUNTIME_MEAS = "CLEAR_RUNTIME_MEAS",
}
