export enum EReduxActionTypes {
  // perspective
  SET_PERSPECTIVE = 'SET_PERSPECTIVE',

  // connection
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  WAIT_FOR_DATA = "WAIT_FOR_DATA",

  // world
  RESET_WORLD = "RESET_WORLD",
  UPDATE_WORLD = "UPDATE_WORLD",

  // ctrl data
  UPDATE_CTRL_DATA = "UPDATE_CTRL_DATA",
  RESET_CTRL_DATA = "RESET_CTRL_DATA",

  // runtime meas
  SHOW_RUNTIME_MEAS = "SHOW_RUNTIME_MEAS",
  HIDE_RUNTIME_MEAS = "HIDE_RUNTIME_MEAS",

  // sensor_storage
  UPDATE_SENSOR_DATA = "UPDATE_SENSOR_DATA",
  RESET_SENSOR_STORAGE = "RESET_SENSOR_STORAGE",
}
